### ISSUE TITLE
aries run can create jobs with the same name when specifying a node list

### ISSUE THREAD

**Issue by jetd1** [eliphatfs/ariesdockerd#1]
The commands below effectively creates jobs with the same name:

```bash
run -g 0 -n aries-00 jet-dev jetd/basic-cuda12.1 -- bash -c 'sleep infinity'
run -g 0 -n aries-01 jet-dev jetd/basic-cuda12.1 -- bash -c 'sleep infinity'
run -g 0 -n aries-02 jet-dev jetd/basic-cuda12.1 -- bash -c 'sleep infinity'
```

When not specifying a node list, this will return `[error] 14 container of same name already exists!` instead (not sure if this behavior is consistent or depending on scheduling).

Another behavior is when you `kill jet-dev`, all jobs with the name would be killed without warning. 

A skim into the client code suggests these behaviors are due to the ws server-side design. Can you clarify if these behaviors are expected?

**Comment by eliphatfs** [comment]
This is indeed not expected, need to be fixed. I think the check in `run` is incomplete when specifying node list.

**Comment by eliphatfs** [comment]
Fixed now. Thank you for the report.
