### ISSUE TITLE
make portfwd more stable and detached from aries main

### ISSUE THREAD

**Issue by jetd1** [eliphatfs/ariesdockerd#2]
Proposals:

1. Allow `aries portfwd` to run in the background (with file-logging, quiet, or verbose options).
2. (Even better) Make `ariesd` a system service so that `portfwd` (registered on a list) can check status and re-register themselves (even if you restart the client). This could allow port-forwarding requests to be passed with the `run` command and stay persistent.

**Comment by eliphatfs** [comment]
Inline CLI functionality has been added. System service is tricky to go because only mainstream linux has a standardized systemd interface...
