### ISSUE TITLE
portfwd should check if container exists at entry

### ISSUE THREAD

**Issue by jetd1** [eliphatfs/ariesdockerd#3]
You can now run a portfwd to a container which does not exist. This could cause some confusing error.

Should be easy adding a check at https://github.com/eliphatfs/ariesdockerd/blob/4786d7e0be075cc61a4b996fa1e1d59c8976bdf6/ariesdockerd/client.py#L109

**Comment by eliphatfs** [comment]
can do it

**Comment by eliphatfs** [comment]
fixed in port forward v2
